//HintName: MaVe.BusinessRules.Validation.g.cs
// <auto-generated />
using MaVe.BusinessRules;

namespace TestAssembly.BusinessRules.Rules.Validation;

public class AgeMinimum() : BusinessRule<AgeMinimum>(Key, Requirement, Description, Category)
{
    public const string Key = "AGE_MIN";

    public const string Requirement = "Age minimum";

    public const string Description = "User must meet minimum age requirement";

    public const string Category = "Validation";
}

