//HintName: MaVe.BusinessRules.Core.g.cs
// <auto-generated />
using MaVe.BusinessRules;

namespace MyCompanyMyApp.BusinessRules.Rules.Core;

public class SimpleRule() : BusinessRule<SimpleRule>(Key, Requirement, Description, Category)
{
    public const string Key = "SIMPLE";

    public const string Requirement = "Simple rule";

    public const string Description = "Tests assembly name in namespace";

    public const string Category = "Core";
}

