//HintName: MaVe.BusinessRules.MyCategory.g.cs
// <auto-generated />
using MaVe.BusinessRules;

namespace TestAssembly.MaVe.BusinessRules.Rules.MyCategory;

public class SanitizedRule() : BusinessRule<SanitizedRule>(Key, Requirement, Description, Category)
{
    public const string Key = "SANITIZED";

    public const string Requirement = "Category has special chars";

    public const string Description = "Tests namespace sanitization";

    public const string Category = "My Category!";
}

