//HintName: MaVe.BusinessRules.General.g.cs
// <auto-generated />
using MaVe.BusinessRules;

namespace TestAssembly.BusinessRules.Rules.General;

public class GenericRule() : BusinessRule<GenericRule>(Key, Requirement, Description, Category)
{
    public const string Key = "GENERIC";

    public const string Requirement = "A generic rule";

    public const string Description = "Has no category";

    public const string Category = "";
}

public class NullCategoryRule() : BusinessRule<NullCategoryRule>(Key, Requirement, Description, Category)
{
    public const string Key = "NULL_CAT";

    public const string Requirement = "Null category rule";

    public const string Description = "Category is whitespace only";

    public const string Category = "   ";
}

