//HintName: MaVe.BusinessRules.Authentication.g.cs
// <auto-generated />
using MaVe.BusinessRules;

namespace TestAssembly.MaVe.BusinessRules.Rules.Authentication;

public class UserMustBeAuthenticated() : BusinessRule<UserMustBeAuthenticated>(Key, Requirement, Description, Category)
{
    public const string Key = "USER_AUTH";

    public const string Requirement = "User must be authenticated";

    public const string Description = "Validates that the user is authenticated";

    public const string Category = "Authentication";
}

