//HintName: MaVe.BusinessRules.CaseTest.g.cs
// <auto-generated />
using MaVe.BusinessRules;

namespace TestAssembly.MaVe.BusinessRules.Rules.CaseTest;

public class PascalCaseRule() : BusinessRule<PascalCaseRule>(Key, Requirement, Description, Category)
{
    public const string Key = "PASCAL";

    public const string Requirement = "PascalCase properties work";

    public const string Description = "Tests case-insensitive deserialization";

    public const string Category = "CaseTest";
}

