//HintName: MaVe.BusinessRules.Escaping.g.cs
// <auto-generated />
using MaVe.BusinessRules;

namespace TestAssembly.BusinessRules.Rules.Escaping;

public class RuleWithSpecialChars() : BusinessRule<RuleWithSpecialChars>(Key, Requirement, Description, Category)
{
    public const string Key = "SPECIAL";

    public const string Requirement = "Must contain \"quotes\" and \\backslashes";

    public const string Description = "Line1\nLine2\rLine3";

    public const string Category = "Escaping";
}

