//HintName: MaVe.BusinessRules.Authorization.g.cs
// <auto-generated />
using MaVe.BusinessRules;

namespace TestAssembly.MaVe.BusinessRules.Rules.Authorization;

public class UserMustBeAdmin() : BusinessRule<UserMustBeAdmin>(Key, Requirement, Description, Category)
{
    public const string Key = "USER_ADMIN";

    public const string Requirement = "User must have admin privileges";

    public const string Description = "Validates that the user has admin rights";

    public const string Category = "Authorization";
}

