<Project>
  <PropertyGroup>
    <Authors>Mauro Verberkt</Authors>
    <Copyright>Copyright (c) Mauro Verberkt</Copyright>
    <RepositoryUrl>https://github.com/MauroVerberkt/DotnetHelpers</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>

  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Nerdbank.GitVersioning" PrivateAssets="all" />
  </ItemGroup>
</Project>
