using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace MaVe.BusinessRulesGenerator;

/// <summary>
/// Incremental source generator that reads MaVe.BusinessRules.json and emits strongly-typed
/// business rule classes grouped by category.
/// </summary>
[Generator]
public class BusinessRuleSourceGenerator : IIncrementalGenerator
{
    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var jsonFilesWithCompilation = context.AdditionalTextsProvider
            .Where(file => file.Path.EndsWith("MaVe.BusinessRules.json", StringComparison.OrdinalIgnoreCase))
            .Select((file, cancellationToken) => (file.Path, Text: file.GetText(cancellationToken)?.ToString()))
            .Where(tuple => !string.IsNullOrWhiteSpace(tuple.Text))
            .Combine(context.CompilationProvider);

        context.RegisterSourceOutput(jsonFilesWithCompilation, (spc, input) =>
        {
            var (jsonData, compilation) = input;
            try
            {
                var options = new JsonSerializerOptions { PropertyNameCaseInsensitive = true };
                var businessRulesConfig = JsonSerializer.Deserialize<BusinessRulesConfig>(jsonData.Text!, options);
                if (businessRulesConfig?.BusinessRules == null || businessRulesConfig.BusinessRules.Count == 0)
                {
                    return;
                }

                var assemblyName = SanitizeNamespace(compilation.AssemblyName ?? "Default");

                // Group rules by category and generate separate files
                var rulesByCategory = businessRulesConfig.BusinessRules
                    .GroupBy(r => string.IsNullOrWhiteSpace(r.Category) ? "General" : r.Category);

                foreach (var categoryGroup in rulesByCategory)
                {
                    var namespaceName = $"{assemblyName}.BusinessRules.Rules.{SanitizeNamespace(categoryGroup.Key)}";

                    var sourceBuilder = new StringBuilder();
                    sourceBuilder.AppendLine("// <auto-generated />");
                    sourceBuilder.AppendLine("using MaVe.BusinessRules;");
                    sourceBuilder.AppendLine();
                    sourceBuilder.AppendLine($"namespace {namespaceName};");
                    sourceBuilder.AppendLine();

                    foreach (var rule in categoryGroup)
                    {
                        sourceBuilder.AppendLine(
                            $"public class {rule.ClassName}() : BusinessRule<{rule.ClassName}>(Key, Requirement, Description, Category)");
                        sourceBuilder.AppendLine("{");
                        sourceBuilder.AppendLine($"    public const string Key = \"{EscapeString(rule.Key)}\";");
                        sourceBuilder.AppendLine();
                        sourceBuilder.AppendLine(
                            $"    public const string Requirement = \"{EscapeString(rule.Requirement)}\";");
                        sourceBuilder.AppendLine();
                        sourceBuilder.AppendLine(
                            $"    public const string Description = \"{EscapeString(rule.Description)}\";");
                        sourceBuilder.AppendLine();
                        sourceBuilder.AppendLine(
                            $"    public const string Category = \"{EscapeString(rule.Category)}\";");
                        sourceBuilder.AppendLine("}");
                        sourceBuilder.AppendLine();
                    }

                    // Generate separate file per category
                    var fileName = Path.GetFileNameWithoutExtension(jsonData.Path);
                    var hintName = $"{fileName}.{SanitizeNamespace(categoryGroup.Key)}.g.cs";

                    spc.AddSource(hintName, SourceText.From(sourceBuilder.ToString(), Encoding.UTF8));
                }
            }
            catch (JsonException)
            {
            }
        });
    }

    private static string SanitizeNamespace(string category)
    {
        if (string.IsNullOrWhiteSpace(category))
        {
            return "General";
        }

        // Remove invalid characters and ensure valid C# identifier
        var sb = new StringBuilder();
        foreach (var c in category)
        {
            if (char.IsLetterOrDigit(c))
            {
                sb.Append(c);
            }
        }

        var result = sb.ToString();
        if (string.IsNullOrEmpty(result))
        {
            return "General";
        }

        return char.IsDigit(result[0]) ? $"_{result}" : result;
    }

    private static string EscapeString(string value)
    {
        if (string.IsNullOrEmpty(value))
        {
            return string.Empty;
        }

        return value.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\n", "\\n").Replace("\r", "\\r");
    }

    private class BusinessRulesConfig
    {
        [JsonPropertyName("MaVe.BusinessRules")]
        public List<BusinessRuleDefinition>? BusinessRules { get; set; }
    }

    private class BusinessRuleDefinition
    {
        [JsonInclude]
        public string ClassName { get; set; } = string.Empty;

        [JsonInclude]
        public string Key { get; set; } = string.Empty;

        [JsonInclude]
        public string Requirement { get; set; } = string.Empty;

        [JsonInclude]
        public string Description { get; set; } = string.Empty;

        [JsonInclude]
        public string Category { get; set; } = string.Empty;
    }
}
