//HintName: Railyard.Generated.g.cs
// <auto-generated />
#nullable enable
namespace MaVe.Railyard;

public static class RailyardServiceCollectionExtensions
{
    /// <summary>
    /// Registers all discovered Railyard operations and the generated <see cref="IYard"/> implementation.
    /// </summary>
    /// <remarks>
    /// If <see cref="global::System.Text.Json.JsonSerializerOptions"/> is registered in the service provider,
    /// it is used for operation payload serialization and deserialization; otherwise System.Text.Json defaults apply.
    /// </remarks>
    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddRailyard(this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)
    {
        global::System.ArgumentNullException.ThrowIfNull(services);

        global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAdd(services, global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Transient(typeof(global::GreetOperation), typeof(global::GreetOperation)));
        global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAdd(services, global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Singleton(typeof(IYard), serviceProvider => new GeneratedYard((global::Microsoft.Extensions.DependencyInjection.IServiceScopeFactory)(serviceProvider.GetService(typeof(global::Microsoft.Extensions.DependencyInjection.IServiceScopeFactory)) ?? throw new global::System.InvalidOperationException("Service 'global::Microsoft.Extensions.DependencyInjection.IServiceScopeFactory' is not registered.")))));
        return services;
    }
}

internal sealed class GeneratedYard : IYard
{
    private readonly global::Microsoft.Extensions.DependencyInjection.IServiceScopeFactory _scopeFactory;
    private readonly global::System.Collections.Generic.Dictionary<string, global::System.Func<global::System.IServiceProvider, IOperation>> _factoryByName;
    private readonly global::System.Collections.Generic.Dictionary<string, OperationDescriptor> _descriptorByName;

    public GeneratedYard(global::Microsoft.Extensions.DependencyInjection.IServiceScopeFactory scopeFactory)
    {
        _scopeFactory = scopeFactory;
        _factoryByName = new global::System.Collections.Generic.Dictionary<string, global::System.Func<global::System.IServiceProvider, IOperation>>(global::System.StringComparer.Ordinal)
        {
            ["greet"] = sp => (IOperation)(sp.GetService(typeof(global::GreetOperation)) ?? throw new global::System.InvalidOperationException("Service 'global::GreetOperation' is not registered.")),
        };

        _descriptorByName = new global::System.Collections.Generic.Dictionary<string, OperationDescriptor>(global::System.StringComparer.Ordinal)
        {
            ["greet"] = new OperationDescriptor("greet", "Greets a user"),
        };

        Manifest = global::System.Array.AsReadOnly(global::System.Linq.Enumerable.ToArray(global::System.Linq.Enumerable.OrderBy(_descriptorByName.Values, descriptor => descriptor.Name, global::System.StringComparer.Ordinal)));
    }

    public global::System.Collections.Generic.IReadOnlyList<OperationDescriptor> Manifest { get; }

    public OperationDescriptor? TryGetDescriptor(string operationName)
    {
        global::System.ArgumentNullException.ThrowIfNull(operationName);
        return _descriptorByName.TryGetValue(operationName, out var descriptor) ? descriptor : null;
    }

    public async global::System.Threading.Tasks.Task<global::MaVe.Monads.Result<string>> DispatchAsync(string operationName, string jsonInput, global::System.Threading.CancellationToken ct = default)
    {
        global::System.ArgumentNullException.ThrowIfNull(operationName);
        global::System.ArgumentNullException.ThrowIfNull(jsonInput);

        if (!_factoryByName.TryGetValue(operationName, out var factory))
        {
            return global::MaVe.Monads.Result.Failure<string>(RailyardErrors.OperationNotFound(operationName));
        }

        using var scope = _scopeFactory.CreateScope();
        var scopedServiceProvider = scope.ServiceProvider;
        var operation = factory(scopedServiceProvider);
        var serializerOptions = scopedServiceProvider.GetService(typeof(global::System.Text.Json.JsonSerializerOptions)) as global::System.Text.Json.JsonSerializerOptions;
        var result = await operation.PerformAsync(jsonInput, serializerOptions, ct).ConfigureAwait(false);
        if (result.IsSuccess)
        {
            return result;
        }

        var contextualizedError = result.Error! with { Message = $"Operation '{operationName}': {result.Error.Message}" };
        return global::MaVe.Monads.Result.Failure<string>(contextualizedError);
    }
}
