import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        'getting-started/installation',
        'getting-started/quick-start',
      ],
    },
    {
      type: 'category',
      label: 'Monads',
      items: [
        'monads/overview',
        {
          type: 'category',
          label: 'Result<T>',
          items: [{type: 'autogenerated', dirName: 'monads/result'}],
        },
        {
          type: 'category',
          label: 'Option<T>',
          items: [{type: 'autogenerated', dirName: 'monads/option'}],
        },
      ],
    },
    {
      type: 'category',
      label: 'Business Rules',
      items: [
        'business-rules/overview',
        'business-rules/result-extensions',
        'business-rules/wcf-integration',
      ],
    },
    {
      type: 'category',
      label: 'Unions',
      items: [
        'unions/overview',
        'unions/getting-started',
        'unions/match-and-switch',
        'unions/analyzers',
      ],
    },
    {
      type: 'category',
      label: 'Railyard',
      items: [
        'railyard/overview',
        'railyard/getting-started',
        'railyard/pipeline',
        'railyard/diagnostics',
      ],
    },
  ],
};

export default sidebars;
