import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  architectureSidebar: [
    'overview',
    {
      type: 'category',
      label: 'By Project',
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'by-project/helper-monads',
          label: 'Monads',
        },
        {
          type: 'doc',
          id: 'by-project/business-rules',
          label: 'BusinessRules',
        },
        {
          type: 'doc',
          id: 'by-project/helper-unions',
          label: 'Unions',
        },
      ],
    },
    {
      type: 'category',
      label: 'Proposals',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'Active',
          collapsed: false,
          items: [{type: 'autogenerated', dirName: 'proposals/active'}],
        },
        {
          type: 'category',
          label: 'Completed',
          collapsed: true,
          items: [{type: 'autogenerated', dirName: 'proposals/completed'}],
        },
      ],
    },
    {
      type: 'category',
      label: 'Decisions (ADRs)',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'decisions'}],
    },
    {
      type: 'category',
      label: 'Design',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'design'}],
    },
    {
      type: 'category',
      label: 'Ways of Working',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'ways-of-working'}],
    },
  ],
};

export default sidebars;
