using System.Diagnostics.CodeAnalysis;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace MaVe.UnionsGenerator;

/// <summary>
/// Generates Unions source code for union declarations.
/// </summary>
[Generator]
public sealed class UnionSourceGenerator : IIncrementalGenerator
{
    private const string UnionAttributeFullyQualifiedName = "MaVe.Unions.UnionAttribute";

    /// <summary>
    /// Initializes the source generator pipeline.
    /// </summary>
    /// <param name="context">Generator initialization context.</param>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var unionRecords = context.SyntaxProvider
            .CreateSyntaxProvider(static (node, _) => node is RecordDeclarationSyntax { AttributeLists.Count: > 0 },
                static (syntaxContext, _) => GetUnionCandidate(syntaxContext))
            .Where(static candidate => candidate is not null)
            .Select(static (candidate, _) => candidate!);

        context.RegisterSourceOutput(unionRecords, static (productionContext, candidate) =>
        {
            if (candidate.Variants.Count == 0)
            {
                return;
            }

            var source = GenerateAbstractBase(candidate);
            productionContext.AddSource($"{candidate.HintName}.UnionBase.g.cs", SourceText.From(source, Encoding.UTF8));
        });
    }

    private static UnionCandidate? GetUnionCandidate(GeneratorSyntaxContext syntaxContext)
    {
        if (syntaxContext.Node is not RecordDeclarationSyntax recordDeclaration)
        {
            return null;
        }

        if (ModelExtensions.GetDeclaredSymbol(syntaxContext.SemanticModel, recordDeclaration) is not INamedTypeSymbol
            unionSymbol)
        {
            return null;
        }

        if (!HasUnionAttribute(unionSymbol) || !IsPartial(recordDeclaration))
        {
            return null;
        }

        var variants = unionSymbol
            .GetTypeMembers()
            .Where(typeMember =>
                typeMember.IsRecord &&
                typeMember.IsSealed &&
                SymbolEqualityComparer.Default.Equals(typeMember.BaseType, unionSymbol))
            .Select(CreateVariant)
            .ToList();

        return new UnionCandidate(
            unionSymbol.ContainingNamespace.IsGlobalNamespace
                ? null
                : unionSymbol.ContainingNamespace.ToDisplayString(),
            GetContainingTypeChain(unionSymbol),
            BuildRecordDeclaration(unionSymbol),
            unionSymbol.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat).Replace('<', '_')
                .Replace('>', '_'),
            variants);
    }

    private static bool HasUnionAttribute(INamedTypeSymbol unionSymbol)
    {
        return unionSymbol
            .GetAttributes()
            .Any(attribute =>
                attribute.AttributeClass?.ToDisplayString() == UnionAttributeFullyQualifiedName);
    }

    private static bool IsPartial(RecordDeclarationSyntax recordDeclaration)
    {
        return recordDeclaration.Modifiers.Any(static modifier => modifier.IsKind(SyntaxKind.PartialKeyword));
    }

    private static string GenerateAbstractBase(UnionCandidate candidate)
    {
        var sourceBuilder = new StringBuilder();

        sourceBuilder.AppendLine("// <auto-generated />");
        sourceBuilder.AppendLine("#nullable enable");
        sourceBuilder.AppendLine("#pragma warning disable CS1591");
        sourceBuilder.AppendLine();

        if (candidate.Namespace is not null)
        {
            sourceBuilder.AppendLine($"namespace {candidate.Namespace};");
            sourceBuilder.AppendLine();
        }

        foreach (var containingType in candidate.ContainingTypeChain)
        {
            sourceBuilder.AppendLine($"{containingType}");
            sourceBuilder.AppendLine("{");
        }

        sourceBuilder.AppendLine($"{candidate.Declaration}");
        sourceBuilder.AppendLine("{");
        sourceBuilder.AppendLine("    private " + ExtractRecordName(candidate.Declaration) + "() { }");
        sourceBuilder.AppendLine();

        AppendIsProperties(sourceBuilder, candidate.Variants);
        sourceBuilder.AppendLine();
        AppendTryGetMethods(sourceBuilder, candidate.Variants);
        sourceBuilder.AppendLine();
        AppendMatchBuilder(sourceBuilder, ExtractRecordName(candidate.Declaration), candidate.Variants);
        sourceBuilder.AppendLine();
        AppendSwitchBuilder(sourceBuilder, ExtractRecordName(candidate.Declaration), candidate.Variants);
        sourceBuilder.AppendLine();
        AppendMatchAsyncBuilder(sourceBuilder, ExtractRecordName(candidate.Declaration), candidate.Variants);
        sourceBuilder.AppendLine();
        AppendSwitchAsyncBuilder(sourceBuilder, ExtractRecordName(candidate.Declaration), candidate.Variants);
        sourceBuilder.AppendLine("}");

        for (var i = candidate.ContainingTypeChain.Count - 1; i >= 0; i--)
        {
            sourceBuilder.AppendLine("}");
        }

        return sourceBuilder.ToString();
    }

    private static void AppendIsProperties(StringBuilder sourceBuilder, IReadOnlyList<UnionVariant> variants)
    {
        foreach (var variant in variants)
        {
            sourceBuilder.AppendLine($"    public bool Is{variant.Name} => this is {variant.Name};");
        }
    }

    private static void AppendTryGetMethods(StringBuilder sourceBuilder, IReadOnlyList<UnionVariant> variants)
    {
        var methods = variants.Where(variant => variant.Parameters.Count > 0).ToList();
        for (var i = 0; i < methods.Count; i++)
        {
            var variant = methods[i];
            var outParameters = string.Join(", ",
                variant.Parameters.Select(parameter => $"out {parameter.TypeName} {parameter.ParameterName}"));

            sourceBuilder.AppendLine($"    public bool TryGet{variant.Name}({outParameters})");
            sourceBuilder.AppendLine("    {");
            sourceBuilder.AppendLine($"        if (this is {variant.Name} variant)");
            sourceBuilder.AppendLine("        {");

            foreach (var parameter in variant.Parameters)
            {
                sourceBuilder.AppendLine($"            {parameter.ParameterName} = variant.{parameter.PropertyName};");
            }

            sourceBuilder.AppendLine("            return true;");
            sourceBuilder.AppendLine("        }");

            foreach (var parameter in variant.Parameters)
            {
                sourceBuilder.AppendLine($"        {parameter.ParameterName} = default!;");
            }

            sourceBuilder.AppendLine("        return false;");
            sourceBuilder.AppendLine("    }");

            if (i < methods.Count - 1)
            {
                sourceBuilder.AppendLine();
            }
        }
    }

    private static void AppendMatchBuilder(StringBuilder sourceBuilder, string unionName,
        IReadOnlyList<UnionVariant> variants)
    {
        sourceBuilder.AppendLine("    public __MatchBuilder_0 Match() => new __MatchBuilder_0(this);");
        sourceBuilder.AppendLine();

        for (var stage = 0; stage < variants.Count; stage++)
        {
            AppendMatchBuilderStage(sourceBuilder, unionName, stage, variants);
            sourceBuilder.AppendLine();
        }

        AppendMatchBuilderFinalStage(sourceBuilder, variants, unionName);
    }

    private static void AppendMatchBuilderStage(StringBuilder sourceBuilder, string unionName, int stage,
        IReadOnlyList<UnionVariant> variants)
    {
        var currentVariant = variants[stage];
        var builderName = $"__MatchBuilder_{stage}";
        var nextBuilderName = $"__MatchBuilder_{stage + 1}";
        var isFirstStage = stage == 0;
        var genericSuffix = isFirstStage ? string.Empty : "<TResult>";

        sourceBuilder.AppendLine($"    public readonly struct {builderName}{genericSuffix}");
        sourceBuilder.AppendLine("    {");
        sourceBuilder.AppendLine("        private readonly " + unionName + " _value;");

        for (var i = 0; i < stage; i++)
        {
            sourceBuilder.AppendLine($"        private readonly {GetMatchHandlerType(variants[i], true)} _handler{i};");
        }

        sourceBuilder.AppendLine();

        var constructorParameters = new List<string> { unionName + " value" };
        for (var i = 0; i < stage; i++)
        {
            constructorParameters.Add($"{GetMatchHandlerType(variants[i], true)} handler{i}");
        }

        sourceBuilder.AppendLine($"        internal {builderName}({string.Join(", ", constructorParameters)})");
        sourceBuilder.AppendLine("        {");
        sourceBuilder.AppendLine("            _value = value;");
        for (var i = 0; i < stage; i++)
        {
            sourceBuilder.AppendLine($"            _handler{i} = handler{i};");
        }

        sourceBuilder.AppendLine("        }");
        sourceBuilder.AppendLine();

        var methodResultType = stage == 0 ? "<TResult>" : string.Empty;
        sourceBuilder.AppendLine(
            $"        public {nextBuilderName}<TResult> {currentVariant.Name}{methodResultType}({GetMatchHandlerType(currentVariant, true)} handler)");
        sourceBuilder.AppendLine("        {");

        var nextConstructorArgs = new List<string> { "_value" };
        for (var i = 0; i < stage; i++)
        {
            nextConstructorArgs.Add($"_handler{i}");
        }

        nextConstructorArgs.Add("handler");

        sourceBuilder.AppendLine(
            $"            return new {nextBuilderName}<TResult>({string.Join(", ", nextConstructorArgs)});");
        sourceBuilder.AppendLine("        }");

        if (currentVariant.Parameters.Count == 0 && stage > 0)
        {
            sourceBuilder.AppendLine();
            sourceBuilder.AppendLine(
                $"        public {nextBuilderName}<TResult> {currentVariant.Name}{methodResultType}(TResult value)");
            sourceBuilder.AppendLine("        {");
            sourceBuilder.AppendLine($"            return {currentVariant.Name}{methodResultType}(() => value);");
            sourceBuilder.AppendLine("        }");
        }

        sourceBuilder.AppendLine("    }");
    }

    private static void AppendMatchBuilderFinalStage(StringBuilder sourceBuilder, IReadOnlyList<UnionVariant> variants,
        string unionName)
    {
        var finalBuilderName = $"__MatchBuilder_{variants.Count}";
        sourceBuilder.AppendLine($"    public readonly struct {finalBuilderName}<TResult>");
        sourceBuilder.AppendLine("    {");
        sourceBuilder.AppendLine($"        private readonly {unionName} _value;");
        for (var i = 0; i < variants.Count; i++)
        {
            sourceBuilder.AppendLine($"        private readonly {GetMatchHandlerType(variants[i], true)} _handler{i};");
        }

        sourceBuilder.AppendLine();

        var constructorParameters = new List<string> { unionName + " value" };
        for (var i = 0; i < variants.Count; i++)
        {
            constructorParameters.Add($"{GetMatchHandlerType(variants[i], true)} handler{i}");
        }

        sourceBuilder.AppendLine($"        internal {finalBuilderName}({string.Join(", ", constructorParameters)})");
        sourceBuilder.AppendLine("        {");
        sourceBuilder.AppendLine("            _value = value;");
        for (var i = 0; i < variants.Count; i++)
        {
            sourceBuilder.AppendLine($"            _handler{i} = handler{i};");
        }

        sourceBuilder.AppendLine("        }");
        sourceBuilder.AppendLine();

        sourceBuilder.AppendLine("        public TResult Result()");
        sourceBuilder.AppendLine("        {");
        sourceBuilder.AppendLine("            return _value switch");
        sourceBuilder.AppendLine("            {");

        for (var i = 0; i < variants.Count; i++)
        {
            var variant = variants[i];
            var invoke = variant.Parameters.Count == 0
                ? $"_handler{i}()"
                : $"_handler{i}({string.Join(", ", variant.Parameters.Select(parameter => "variant." + parameter.PropertyName))})";

            var pattern = variant.Parameters.Count == 0
                ? $"{variant.Name} _"
                : $"{variant.Name} variant";

            sourceBuilder.AppendLine($"                {pattern} => {invoke},");
        }

        sourceBuilder.AppendLine(
            "                _ => throw new global::System.InvalidOperationException(\"Unrecognized union variant.\")");
        sourceBuilder.AppendLine("            };");
        sourceBuilder.AppendLine("        }");
        sourceBuilder.AppendLine("    }");
    }

    private static string GetMatchHandlerType(UnionVariant variant, bool includeResultType)
    {
        var parameterTypes = variant.Parameters.Select(parameter => parameter.TypeName).ToList();
        if (includeResultType)
        {
            parameterTypes.Add("TResult");
        }

        return $"global::System.Func<{string.Join(", ", parameterTypes)}>";
    }

    private static void AppendMatchAsyncBuilder(StringBuilder sourceBuilder, string unionName,
        IReadOnlyList<UnionVariant> variants)
    {
        sourceBuilder.AppendLine("    public __MatchAsyncBuilder_0 MatchAsync() => new __MatchAsyncBuilder_0(this);");
        sourceBuilder.AppendLine();

        for (var stage = 0; stage < variants.Count; stage++)
        {
            AppendMatchAsyncBuilderStage(sourceBuilder, unionName, stage, variants);
            sourceBuilder.AppendLine();
        }

        AppendMatchAsyncBuilderFinalStage(sourceBuilder, variants, unionName);
    }

    private static void AppendMatchAsyncBuilderStage(StringBuilder sourceBuilder, string unionName, int stage,
        IReadOnlyList<UnionVariant> variants)
    {
        var currentVariant = variants[stage];
        var builderName = $"__MatchAsyncBuilder_{stage}";
        var nextBuilderName = $"__MatchAsyncBuilder_{stage + 1}";
        var isFirstStage = stage == 0;
        var genericSuffix = isFirstStage ? string.Empty : "<TResult>";

        sourceBuilder.AppendLine($"    public readonly struct {builderName}{genericSuffix}");
        sourceBuilder.AppendLine("    {");
        sourceBuilder.AppendLine("        private readonly " + unionName + " _value;");

        for (var i = 0; i < stage; i++)
        {
            sourceBuilder.AppendLine(
                $"        private readonly {GetMatchAsyncHandlerType(variants[i], true)} _handler{i};");
        }

        sourceBuilder.AppendLine();

        var constructorParameters = new List<string> { unionName + " value" };
        for (var i = 0; i < stage; i++)
        {
            constructorParameters.Add($"{GetMatchAsyncHandlerType(variants[i], true)} handler{i}");
        }

        sourceBuilder.AppendLine($"        internal {builderName}({string.Join(", ", constructorParameters)})");
        sourceBuilder.AppendLine("        {");
        sourceBuilder.AppendLine("            _value = value;");
        for (var i = 0; i < stage; i++)
        {
            sourceBuilder.AppendLine($"            _handler{i} = handler{i};");
        }

        sourceBuilder.AppendLine("        }");
        sourceBuilder.AppendLine();

        var methodResultType = stage == 0 ? "<TResult>" : string.Empty;
        sourceBuilder.AppendLine(
            $"        public {nextBuilderName}<TResult> {currentVariant.Name}{methodResultType}({GetMatchAsyncHandlerType(currentVariant, true)} handler)");
        sourceBuilder.AppendLine("        {");

        var nextConstructorArgs = new List<string> { "_value" };
        for (var i = 0; i < stage; i++)
        {
            nextConstructorArgs.Add($"_handler{i}");
        }

        nextConstructorArgs.Add("handler");

        sourceBuilder.AppendLine(
            $"            return new {nextBuilderName}<TResult>({string.Join(", ", nextConstructorArgs)});");
        sourceBuilder.AppendLine("        }");

        if (currentVariant.Parameters.Count == 0 && stage > 0)
        {
            sourceBuilder.AppendLine();
            sourceBuilder.AppendLine(
                $"        public {nextBuilderName}<TResult> {currentVariant.Name}{methodResultType}(TResult value)");
            sourceBuilder.AppendLine("        {");
            sourceBuilder.AppendLine(
                $"            return {currentVariant.Name}{methodResultType}(() => global::System.Threading.Tasks.Task.FromResult(value));");
            sourceBuilder.AppendLine("        }");
        }

        sourceBuilder.AppendLine("    }");
    }

    private static void AppendMatchAsyncBuilderFinalStage(StringBuilder sourceBuilder,
        IReadOnlyList<UnionVariant> variants, string unionName)
    {
        var finalBuilderName = $"__MatchAsyncBuilder_{variants.Count}";
        sourceBuilder.AppendLine($"    public readonly struct {finalBuilderName}<TResult>");
        sourceBuilder.AppendLine("    {");
        sourceBuilder.AppendLine($"        private readonly {unionName} _value;");
        for (var i = 0; i < variants.Count; i++)
        {
            sourceBuilder.AppendLine(
                $"        private readonly {GetMatchAsyncHandlerType(variants[i], true)} _handler{i};");
        }

        sourceBuilder.AppendLine();

        var constructorParameters = new List<string> { unionName + " value" };
        for (var i = 0; i < variants.Count; i++)
        {
            constructorParameters.Add($"{GetMatchAsyncHandlerType(variants[i], true)} handler{i}");
        }

        sourceBuilder.AppendLine($"        internal {finalBuilderName}({string.Join(", ", constructorParameters)})");
        sourceBuilder.AppendLine("        {");
        sourceBuilder.AppendLine("            _value = value;");
        for (var i = 0; i < variants.Count; i++)
        {
            sourceBuilder.AppendLine($"            _handler{i} = handler{i};");
        }

        sourceBuilder.AppendLine("        }");
        sourceBuilder.AppendLine();

        sourceBuilder.AppendLine("        public global::System.Threading.Tasks.Task<TResult> ResultAsync()");
        sourceBuilder.AppendLine("        {");
        sourceBuilder.AppendLine("            return _value switch");
        sourceBuilder.AppendLine("            {");

        for (var i = 0; i < variants.Count; i++)
        {
            var variant = variants[i];
            var invoke = variant.Parameters.Count == 0
                ? $"_handler{i}()"
                : $"_handler{i}({string.Join(", ", variant.Parameters.Select(parameter => "variant." + parameter.PropertyName))})";

            var pattern = variant.Parameters.Count == 0
                ? $"{variant.Name} _"
                : $"{variant.Name} variant";

            sourceBuilder.AppendLine($"                {pattern} => {invoke},");
        }

        sourceBuilder.AppendLine(
            "                _ => throw new global::System.InvalidOperationException(\"Unrecognized union variant.\")");
        sourceBuilder.AppendLine("            };");
        sourceBuilder.AppendLine("        }");
        sourceBuilder.AppendLine("    }");
    }

    private static string GetMatchAsyncHandlerType(UnionVariant variant, bool includeResultType)
    {
        var parameterTypes = variant.Parameters.Select(parameter => parameter.TypeName).ToList();
        if (includeResultType)
        {
            parameterTypes.Add("global::System.Threading.Tasks.Task<TResult>");
        }

        return $"global::System.Func<{string.Join(", ", parameterTypes)}>";
    }

    private static void AppendSwitchBuilder(StringBuilder sourceBuilder, string unionName,
        IReadOnlyList<UnionVariant> variants)
    {
        sourceBuilder.AppendLine("    public __SwitchBuilder_0 Switch() => new __SwitchBuilder_0(this);");
        sourceBuilder.AppendLine();

        for (var stage = 0; stage < variants.Count; stage++)
        {
            AppendSwitchBuilderStage(sourceBuilder, unionName, stage, variants);
            sourceBuilder.AppendLine();
        }

        AppendSwitchBuilderFinalStage(sourceBuilder, variants, unionName);
    }

    private static void AppendSwitchBuilderStage(StringBuilder sourceBuilder, string unionName, int stage,
        IReadOnlyList<UnionVariant> variants)
    {
        var currentVariant = variants[stage];
        var builderName = $"__SwitchBuilder_{stage}";
        var nextBuilderName = $"__SwitchBuilder_{stage + 1}";

        sourceBuilder.AppendLine($"    public readonly struct {builderName}");
        sourceBuilder.AppendLine("    {");
        sourceBuilder.AppendLine("        private readonly " + unionName + " _value;");

        for (var i = 0; i < stage; i++)
        {
            sourceBuilder.AppendLine($"        private readonly {GetSwitchHandlerType(variants[i])} _handler{i};");
        }

        sourceBuilder.AppendLine();

        var constructorParameters = new List<string> { unionName + " value" };
        for (var i = 0; i < stage; i++)
        {
            constructorParameters.Add($"{GetSwitchHandlerType(variants[i])} handler{i}");
        }

        sourceBuilder.AppendLine($"        internal {builderName}({string.Join(", ", constructorParameters)})");
        sourceBuilder.AppendLine("        {");
        sourceBuilder.AppendLine("            _value = value;");
        for (var i = 0; i < stage; i++)
        {
            sourceBuilder.AppendLine($"            _handler{i} = handler{i};");
        }

        sourceBuilder.AppendLine("        }");
        sourceBuilder.AppendLine();

        sourceBuilder.AppendLine(
            $"        public {nextBuilderName} {currentVariant.Name}({GetSwitchHandlerType(currentVariant)} handler)");
        sourceBuilder.AppendLine("        {");

        var nextConstructorArgs = new List<string> { "_value" };
        for (var i = 0; i < stage; i++)
        {
            nextConstructorArgs.Add($"_handler{i}");
        }

        nextConstructorArgs.Add("handler");

        sourceBuilder.AppendLine(
            $"            return new {nextBuilderName}({string.Join(", ", nextConstructorArgs)});");
        sourceBuilder.AppendLine("        }");

        sourceBuilder.AppendLine("    }");
    }

    private static void AppendSwitchBuilderFinalStage(StringBuilder sourceBuilder, IReadOnlyList<UnionVariant> variants,
        string unionName)
    {
        var finalBuilderName = $"__SwitchBuilder_{variants.Count}";
        sourceBuilder.AppendLine($"    public readonly struct {finalBuilderName}");
        sourceBuilder.AppendLine("    {");
        sourceBuilder.AppendLine($"        private readonly {unionName} _value;");
        for (var i = 0; i < variants.Count; i++)
        {
            sourceBuilder.AppendLine($"        private readonly {GetSwitchHandlerType(variants[i])} _handler{i};");
        }

        sourceBuilder.AppendLine();

        var constructorParameters = new List<string> { unionName + " value" };
        for (var i = 0; i < variants.Count; i++)
        {
            constructorParameters.Add($"{GetSwitchHandlerType(variants[i])} handler{i}");
        }

        sourceBuilder.AppendLine($"        internal {finalBuilderName}({string.Join(", ", constructorParameters)})");
        sourceBuilder.AppendLine("        {");
        sourceBuilder.AppendLine("            _value = value;");
        for (var i = 0; i < variants.Count; i++)
        {
            sourceBuilder.AppendLine($"            _handler{i} = handler{i};");
        }

        sourceBuilder.AppendLine("        }");
        sourceBuilder.AppendLine();

        sourceBuilder.AppendLine("        public void Execute()");
        sourceBuilder.AppendLine("        {");
        sourceBuilder.AppendLine("            switch (_value)");
        sourceBuilder.AppendLine("            {");

        for (var i = 0; i < variants.Count; i++)
        {
            var variant = variants[i];
            var invoke = variant.Parameters.Count == 0
                ? $"_handler{i}()"
                : $"_handler{i}({string.Join(", ", variant.Parameters.Select(parameter => "variant." + parameter.PropertyName))})";

            var pattern = variant.Parameters.Count == 0
                ? $"{variant.Name} _"
                : $"{variant.Name} variant";

            sourceBuilder.AppendLine($"                case {pattern}:");
            sourceBuilder.AppendLine($"                    {invoke};");
            sourceBuilder.AppendLine("                    break;");
        }

        sourceBuilder.AppendLine("                default:");
        sourceBuilder.AppendLine(
            "                    throw new global::System.InvalidOperationException(\"Unrecognized union variant.\");");
        sourceBuilder.AppendLine("            }");
        sourceBuilder.AppendLine("        }");
        sourceBuilder.AppendLine("    }");
    }

    private static string GetSwitchHandlerType(UnionVariant variant)
    {
        if (variant.Parameters.Count == 0)
        {
            return "global::System.Action";
        }

        return
            $"global::System.Action<{string.Join(", ", variant.Parameters.Select(parameter => parameter.TypeName))}>";
    }

    private static void AppendSwitchAsyncBuilder(StringBuilder sourceBuilder, string unionName,
        IReadOnlyList<UnionVariant> variants)
    {
        sourceBuilder.AppendLine(
            "    public __SwitchAsyncBuilder_0 SwitchAsync() => new __SwitchAsyncBuilder_0(this);");
        sourceBuilder.AppendLine();

        for (var stage = 0; stage < variants.Count; stage++)
        {
            AppendSwitchAsyncBuilderStage(sourceBuilder, unionName, stage, variants);
            sourceBuilder.AppendLine();
        }

        AppendSwitchAsyncBuilderFinalStage(sourceBuilder, variants, unionName);
    }

    private static void AppendSwitchAsyncBuilderStage(StringBuilder sourceBuilder, string unionName, int stage,
        IReadOnlyList<UnionVariant> variants)
    {
        var currentVariant = variants[stage];
        var builderName = $"__SwitchAsyncBuilder_{stage}";
        var nextBuilderName = $"__SwitchAsyncBuilder_{stage + 1}";

        sourceBuilder.AppendLine($"    public readonly struct {builderName}");
        sourceBuilder.AppendLine("    {");
        sourceBuilder.AppendLine("        private readonly " + unionName + " _value;");

        for (var i = 0; i < stage; i++)
        {
            sourceBuilder.AppendLine($"        private readonly {GetSwitchAsyncHandlerType(variants[i])} _handler{i};");
        }

        sourceBuilder.AppendLine();

        var constructorParameters = new List<string> { unionName + " value" };
        for (var i = 0; i < stage; i++)
        {
            constructorParameters.Add($"{GetSwitchAsyncHandlerType(variants[i])} handler{i}");
        }

        sourceBuilder.AppendLine($"        internal {builderName}({string.Join(", ", constructorParameters)})");
        sourceBuilder.AppendLine("        {");
        sourceBuilder.AppendLine("            _value = value;");
        for (var i = 0; i < stage; i++)
        {
            sourceBuilder.AppendLine($"            _handler{i} = handler{i};");
        }

        sourceBuilder.AppendLine("        }");
        sourceBuilder.AppendLine();

        sourceBuilder.AppendLine(
            $"        public {nextBuilderName} {currentVariant.Name}({GetSwitchAsyncHandlerType(currentVariant)} handler)");
        sourceBuilder.AppendLine("        {");

        var nextConstructorArgs = new List<string> { "_value" };
        for (var i = 0; i < stage; i++)
        {
            nextConstructorArgs.Add($"_handler{i}");
        }

        nextConstructorArgs.Add("handler");

        sourceBuilder.AppendLine(
            $"            return new {nextBuilderName}({string.Join(", ", nextConstructorArgs)});");
        sourceBuilder.AppendLine("        }");

        sourceBuilder.AppendLine("    }");
    }

    private static void AppendSwitchAsyncBuilderFinalStage(StringBuilder sourceBuilder,
        IReadOnlyList<UnionVariant> variants, string unionName)
    {
        var finalBuilderName = $"__SwitchAsyncBuilder_{variants.Count}";
        sourceBuilder.AppendLine($"    public readonly struct {finalBuilderName}");
        sourceBuilder.AppendLine("    {");
        sourceBuilder.AppendLine($"        private readonly {unionName} _value;");
        for (var i = 0; i < variants.Count; i++)
        {
            sourceBuilder.AppendLine($"        private readonly {GetSwitchAsyncHandlerType(variants[i])} _handler{i};");
        }

        sourceBuilder.AppendLine();

        var constructorParameters = new List<string> { unionName + " value" };
        for (var i = 0; i < variants.Count; i++)
        {
            constructorParameters.Add($"{GetSwitchAsyncHandlerType(variants[i])} handler{i}");
        }

        sourceBuilder.AppendLine($"        internal {finalBuilderName}({string.Join(", ", constructorParameters)})");
        sourceBuilder.AppendLine("        {");
        sourceBuilder.AppendLine("            _value = value;");
        for (var i = 0; i < variants.Count; i++)
        {
            sourceBuilder.AppendLine($"            _handler{i} = handler{i};");
        }

        sourceBuilder.AppendLine("        }");
        sourceBuilder.AppendLine();

        sourceBuilder.AppendLine("        public global::System.Threading.Tasks.Task ExecuteAsync()");
        sourceBuilder.AppendLine("        {");
        sourceBuilder.AppendLine("            return _value switch");
        sourceBuilder.AppendLine("            {");

        for (var i = 0; i < variants.Count; i++)
        {
            var variant = variants[i];
            var invoke = variant.Parameters.Count == 0
                ? $"_handler{i}()"
                : $"_handler{i}({string.Join(", ", variant.Parameters.Select(parameter => "variant." + parameter.PropertyName))})";

            var pattern = variant.Parameters.Count == 0
                ? $"{variant.Name} _"
                : $"{variant.Name} variant";

            sourceBuilder.AppendLine($"                {pattern} => {invoke},");
        }

        sourceBuilder.AppendLine(
            "                _ => throw new global::System.InvalidOperationException(\"Unrecognized union variant.\")");
        sourceBuilder.AppendLine("            };");
        sourceBuilder.AppendLine("        }");
        sourceBuilder.AppendLine("    }");
    }

    private static string GetSwitchAsyncHandlerType(UnionVariant variant)
    {
        var parameterTypes = variant.Parameters.Select(parameter => parameter.TypeName).ToList();
        parameterTypes.Add("global::System.Threading.Tasks.Task");

        return $"global::System.Func<{string.Join(", ", parameterTypes)}>";
    }

    private static UnionVariant CreateVariant(INamedTypeSymbol variantSymbol)
    {
        var primaryConstructor = variantSymbol.InstanceConstructors
            .FirstOrDefault(constructor => !constructor.IsImplicitlyDeclared);

        var parameters = primaryConstructor is null
            ? []
            : primaryConstructor.Parameters.Select(parameter =>
                {
                    var propertyName = ToPascalCase(parameter.Name);
                    return new UnionVariantParameter(
                        parameter.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                        ToCamelCase(parameter.Name),
                        propertyName);
                })
                .ToList();

        return new UnionVariant(variantSymbol.Name, parameters);
    }

    private static string ToPascalCase(string input)
    {
        if (string.IsNullOrEmpty(input))
        {
            return input;
        }

        if (char.IsUpper(input[0]))
        {
            return input;
        }

        return char.ToUpperInvariant(input[0]) + input.Substring(1);
    }

    private static string ToCamelCase(string input)
    {
        if (string.IsNullOrEmpty(input))
        {
            return input;
        }

        if (char.IsLower(input[0]))
        {
            return input;
        }

        return char.ToLowerInvariant(input[0]) + input.Substring(1);
    }

    private static string BuildRecordDeclaration(INamedTypeSymbol unionSymbol)
    {
        var accessibility = unionSymbol.DeclaredAccessibility switch
        {
            Accessibility.Public => "public",
            Accessibility.Internal => "internal",
            Accessibility.Private => "private",
            Accessibility.Protected => "protected",
            Accessibility.ProtectedAndInternal => "private protected",
            Accessibility.ProtectedOrInternal => "protected internal",
            _ => "internal"
        };

        var typeParameters = unionSymbol.TypeParameters.Length == 0
            ? string.Empty
            : $"<{string.Join(", ", unionSymbol.TypeParameters.Select(typeParameter => typeParameter.Name))}>";

        return $"{accessibility} abstract partial record {unionSymbol.Name}{typeParameters}";
    }

    private static List<string> GetContainingTypeChain(INamedTypeSymbol symbol)
    {
        var chain = new List<string>();
        var current = symbol.ContainingType;

        while (current is not null)
        {
            chain.Insert(0, BuildContainingTypeDeclaration(current));
            current = current.ContainingType;
        }

        return chain;
    }

    private static string BuildContainingTypeDeclaration(INamedTypeSymbol containingType)
    {
        var accessibility = containingType.DeclaredAccessibility switch
        {
            Accessibility.Public => "public",
            Accessibility.Internal => "internal",
            Accessibility.Private => "private",
            Accessibility.Protected => "protected",
            Accessibility.ProtectedAndInternal => "private protected",
            Accessibility.ProtectedOrInternal => "protected internal",
            _ => "internal"
        };

        var kind = containingType.TypeKind == TypeKind.Struct ? "struct" : "class";
        var typeParameters = containingType.TypeParameters.Length == 0
            ? string.Empty
            : $"<{string.Join(", ", containingType.TypeParameters.Select(typeParameter => typeParameter.Name))}>";

        return $"{accessibility} partial {kind} {containingType.Name}{typeParameters}";
    }

    private static string ExtractRecordName(string declaration)
    {
        const string marker = " record ";
        var markerIndex = declaration.IndexOf(marker, StringComparison.Ordinal);
        var nameStartIndex = markerIndex + marker.Length;
        var genericStartIndex = declaration.IndexOf('<', nameStartIndex);

        return genericStartIndex >= 0
            ? declaration.Substring(nameStartIndex, genericStartIndex - nameStartIndex)
            : declaration.Substring(nameStartIndex);
    }

    private sealed class UnionCandidate : IEquatable<UnionCandidate>
    {
        public UnionCandidate(
            string? @namespace,
            IReadOnlyList<string> containingTypeChain,
            string declaration,
            string hintName,
            IReadOnlyList<UnionVariant> variants)
        {
            Namespace = @namespace;
            ContainingTypeChain = containingTypeChain;
            Declaration = declaration;
            HintName = hintName;
            Variants = variants;
        }

        public string? Namespace { get; }

        public IReadOnlyList<string> ContainingTypeChain { get; }

        public string Declaration { get; }

        public string HintName { get; }

        public IReadOnlyList<UnionVariant> Variants { get; }

        public bool Equals(UnionCandidate? other)
        {
            if (other is null)
            {
                return false;
            }

            if (ReferenceEquals(this, other))
            {
                return true;
            }

            return string.Equals(Namespace, other.Namespace, StringComparison.Ordinal)
                   && string.Equals(Declaration, other.Declaration, StringComparison.Ordinal)
                   && string.Equals(HintName, other.HintName, StringComparison.Ordinal)
                   && ContainingTypeChain.SequenceEqual(other.ContainingTypeChain)
                   && Variants.SequenceEqual(other.Variants);
        }

        public override bool Equals(object? obj)
        {
            return Equals(obj as UnionCandidate);
        }

        // Roslyn incremental generator caching uses Equals for state-table comparisons.
        // This GetHashCode implementation exists to satisfy the Equals/GetHashCode contract,
        // but is not invoked by the generator pipeline itself.
        [ExcludeFromCodeCoverage]
        public override int GetHashCode()
        {
            unchecked
            {
                var hashCode = 17;
                hashCode = hashCode * 31 + (Namespace is null ? 0 : StringComparer.Ordinal.GetHashCode(Namespace));
                hashCode = hashCode * 31 + StringComparer.Ordinal.GetHashCode(Declaration);
                hashCode = hashCode * 31 + StringComparer.Ordinal.GetHashCode(HintName);

                foreach (var containingType in ContainingTypeChain)
                {
                    hashCode = hashCode * 31 + StringComparer.Ordinal.GetHashCode(containingType);
                }

                foreach (var variant in Variants)
                {
                    hashCode = hashCode * 31 + variant.GetHashCode();
                }

                return hashCode;
            }
        }
    }

    private sealed class UnionVariant : IEquatable<UnionVariant>
    {
        public UnionVariant(string name, IReadOnlyList<UnionVariantParameter> parameters)
        {
            Name = name;
            Parameters = parameters;
        }

        public string Name { get; }

        public IReadOnlyList<UnionVariantParameter> Parameters { get; }

        public bool Equals(UnionVariant? other)
        {
            if (other is null)
            {
                return false;
            }

            if (ReferenceEquals(this, other))
            {
                return true;
            }

            return string.Equals(Name, other.Name, StringComparison.Ordinal)
                   && Parameters.SequenceEqual(other.Parameters);
        }

        public override bool Equals(object? obj)
        {
            return Equals(obj as UnionVariant);
        }

        // Roslyn incremental generator caching uses Equals for state-table comparisons.
        // This GetHashCode implementation exists to satisfy the Equals/GetHashCode contract,
        // but is not invoked by the generator pipeline itself.
        [ExcludeFromCodeCoverage]
        public override int GetHashCode()
        {
            unchecked
            {
                var hashCode = 17;
                hashCode = hashCode * 31 + StringComparer.Ordinal.GetHashCode(Name);
                foreach (var parameter in Parameters)
                {
                    hashCode = hashCode * 31 + parameter.GetHashCode();
                }

                return hashCode;
            }
        }
    }

    private sealed class UnionVariantParameter : IEquatable<UnionVariantParameter>
    {
        public UnionVariantParameter(string typeName, string parameterName, string propertyName)
        {
            TypeName = typeName;
            ParameterName = parameterName;
            PropertyName = propertyName;
        }

        public string TypeName { get; }

        public string ParameterName { get; }

        public string PropertyName { get; }

        public bool Equals(UnionVariantParameter? other)
        {
            if (other is null)
            {
                return false;
            }

            if (ReferenceEquals(this, other))
            {
                return true;
            }

            return string.Equals(TypeName, other.TypeName, StringComparison.Ordinal)
                   && string.Equals(ParameterName, other.ParameterName, StringComparison.Ordinal)
                   && string.Equals(PropertyName, other.PropertyName, StringComparison.Ordinal);
        }

        public override bool Equals(object? obj)
        {
            return Equals(obj as UnionVariantParameter);
        }

        // Roslyn incremental generator caching uses Equals for state-table comparisons.
        // This GetHashCode implementation exists to satisfy the Equals/GetHashCode contract,
        // but is not invoked by the generator pipeline itself.
        [ExcludeFromCodeCoverage]
        public override int GetHashCode()
        {
            unchecked
            {
                var hashCode = 17;
                hashCode = hashCode * 31 + StringComparer.Ordinal.GetHashCode(TypeName);
                hashCode = hashCode * 31 + StringComparer.Ordinal.GetHashCode(ParameterName);
                hashCode = hashCode * 31 + StringComparer.Ordinal.GetHashCode(PropertyName);
                return hashCode;
            }
        }
    }
}
