<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\src\BusinessRules.ResultExtensions\BusinessRules.ResultExtensions.csproj"/>
    <ProjectReference Include="..\..\src\BusinessRules\BusinessRules.csproj"/>
    <ProjectReference Include="..\..\src\Monads\Monads.csproj"/>
  </ItemGroup>

</Project>
